In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_squared_error, r2_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import preprocessing
from sklearn import svm

In [3]:
col_names = ['Sex','School','Grade','Father work','Mother work','Income','Domicile','Major','label']
# load dataset
pima = pd.read_csv("PJ_F.csv", header=None, names=col_names)

In [4]:
pima.head()

Sex  School  Grade  Father work  Mother work  Income  Domicile  Major  \
0    1       1   2.61            1            6       6         0      2   
1    0       2   3.22            0            5       2         0      0   
2    1       1   3.55            0            5       1         0      0   
3    1       1   2.55            1            3       5         0      0   
4    1       1   3.15            3            4       3         0      6   

   label  
0      1  
1      1  
2      1  
3      1  
4      0

In [42]:
#split dataset in features and target variable
feature_cols = ['Sex','School','Grade','Income','Domicile','Major']
X = pima[feature_cols] # Features
y = pima.label # Target variable

In [43]:
# Split dataset into training set and test set"
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,) # 70% training and 30% test

In [44]:
# Fitting the Transformer APIPython
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [45]:
clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [46]:
clf_svm_scaled = svm.SVC(kernel='linear')
clf_svm_scaled.fit(X_train_scaled, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [47]:
y_pred = clf_svm.predict(X_test)  
y_pred

array([0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [48]:
y_pred_scaled = clf_svm_scaled.predict(X_test_scaled)  
y_pred_scaled

array([0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [49]:
print('Non Standardize')
print('Accuracy of SVM classifier on training set: {:.4f}'
     .format(clf_svm.score(X_train, y_train)*100))
print('Accuracy of SVM classifier on test set: {:.4f}'
     .format(clf_svm.score(X_test, y_test)*100))
print('\nStandardize')
print('Accuracy of SVM classifier on training set: {:.4f}'
     .format(clf_svm_scaled.score(X_train_scaled, y_train)*100))
print('Accuracy of SVM classifier on test set: {:.4f}'
     .format(clf_svm_scaled.score(X_test_scaled, y_test)*100))

Non Standardize
Accuracy of SVM classifier on training set: 84.7059
Accuracy of SVM classifier on test set: 78.0822

Standardize
Accuracy of SVM classifier on training set: 86.4706
Accuracy of SVM classifier on test set: 78.0822


In [50]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred_scaled))
print(confusion_matrix(y_test,y_pred_scaled))

              precision    recall  f1-score   support

           0       0.68      0.90      0.77        30
           1       0.91      0.70      0.79        43

    accuracy                           0.78        73
   macro avg       0.79      0.80      0.78        73
weighted avg       0.81      0.78      0.78        73

[[27  3]
 [13 30]]


In [51]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7808219178082192


In [52]:
# Evaluate the model's accuracy
print("Train set accuracy = " + str(clf_svm.score(X_train, y_train)))
print("Test set accuracy = " + str(clf_svm.score(X_test, y_test)))

Train set accuracy = 0.8470588235294118
Test set accuracy = 0.7808219178082192
